### ISSUE TITLE
Remove CircleCi docs builds

### ISSUE THREAD

**Issue by GeorgianaElena** [jupyterhub/traefik-proxy#118]
traefik-proxy still uses CircleCi to build its docs. We should should enable RTD builds instead.

**Comment by GeorgianaElena** [comment]
@minrk, I believe you are the maintainer for the `traefik-proxy` rtd project (https://readthedocs.org/projects/jupyterhub-traefik-proxy/). Do you want to add me there too? I would love to enable to enable PR RTD builds and previews for the repo <3

Also, the docs build is currently failing and I want to investigate it :(

**Comment by minrk** [comment]
I added you and a few others to RTD. The docs builds are failing due to #116, which I'll open a PR to resolve shortly. Short answer: dependabot is only for applications, not libraries.

**Comment by GeorgianaElena** [comment]
> I added you and a few others to RTD

Thank you @minrk! I also noticed that you also enabled RTD PR builds <3 so I'll open a PR to remove the CircleCI docs build.
