### ISSUE TITLE
Release a new version of traefik-proxy

### ISSUE THREAD

**Issue by GeorgianaElena** [jupyterhub/traefik-proxy#123]
### Proposed change

It has been [a while](https://github.com/jupyterhub/traefik-proxy/blob/master/docs/source/changelog.rst) since the latest `traefik-proxy` release. Though most of the changes that [happened](https://github.com/jupyterhub/traefik-proxy/compare/0.1.6...master) were mostly related to tests and CI/CD, there are two fixes that I believe should be made available: 
* https://github.com/jupyterhub/traefik-proxy/pull/110
* https://github.com/jupyterhub/traefik-proxy/pull/115

### Alternative options

Still use the 0.1.6 version.

### Who would use this feature?

Everyone that uses `jupyterhub-traefik-proxy`, so mostly TLJH :)
TLJH unit tests don't run anymore because of a pkg version pin related to `traefik-proxy`.

**Comment by consideRatio** [comment]
Sounds great to me! It seems like the only thing to do is to create a changelog and push a tag because the GitHub workflow is in place, the PYPI_TOKEN is in place, and RELEASE.md is in place!

**Comment by consideRatio** [comment]
I guess this may be 0.2.0 then if some dependency pinning of relevance changed? Perhaps 1.0.0? I really appreciate being able to version control with major/minor/patch and not only minor/patch.

**Comment by GeorgianaElena** [comment]
>  It seems like the only thing to do is to create a changelog and push a tag because the GitHub workflow is in place, the PYPI_TOKEN is in place, and RELEASE.md is in place!

Yep :heart:

> I guess this may be 0.2.0 then if some dependency pinning of relevance changed? Perhaps 1.0.0? I really appreciate being able to version control with major/minor/patch and not only minor/patch.

I've been thinking about this too. I would say to have this one be `0.2.0` and switch to `1.0.0` when we switch from Traefik API v1 to Traefik API v2. I believe that will be a quite major change. What do you think?

**Comment by consideRatio** [comment]
Sure @GeorgianaElena! I think either would be fine!

**Comment by GeorgianaElena** [comment]
This has just happened https://pypi.org/project/jupyterhub-traefik-proxy/ :rocket:
