### ISSUE TITLE
Add toml as a direct dependency

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/traefik-proxy#126]
### Bug description

Our installer uses toml directly, but we rely on getting it via jupyter-traefik-proxy. We should make it a direct dependency, by specifying it in `setup.py`

#### Expected behaviour

`setup.py` directly refers to toml as a direct dependency

#### Actual behaviour

We only specify `jupyter-server-proxy`, and that indirectly brings in `toml`.

**Comment by manics** [comment]
It's included in setup.py via requirements.txt:
https://github.com/jupyterhub/traefik-proxy/blob/ec8eadcc7d274911d8e5bdcbed9082c02edd642f/requirements.txt#L5
