### ISSUE TITLE
Test all possible downloadable versions in installer automatically

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/traefik-proxy#130]
Right now, our installer tests only cover a subset of the URLs + hashes we make available. This makes it possible for a new traefik / etcd / consul version to slip through with wrong hashes, and we won't notice until it breaks someone somewhere.

### Proposed change

Right now, everything is an integration test. We should add a unit test as well, that imports the constants / functions in `jupyterhub_traefik_proxy/install.py`, and test all of them.

### Who would use this feature?

Anyone adding new entries to list of downloadable packages.

**Comment by consideRatio** [comment]
The intermittent errors we had related to a mistake in the TLJH and didn't have anything to do with traefik-proxy!

**Comment by minrk** [comment]
Closing this as the constants are gone, and all traefik versions are supported in #160
