### ISSUE TITLE
Move away from versioneer, towards tbump

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/traefik-proxy#159]
In @minrk [commented about versioneer](https://github.com/jupyterhub/traefik-proxy/pull/157#discussion_r1114477739), and I'd like to propose that we transition away from it towards using `tbump` like in several other repos.

As an example on using tbump, see these files from jupyterhub-idle-culler where I recently introduced it:

- https://github.com/jupyterhub/jupyterhub-idle-culler/blob/main/pyproject.toml
- https://github.com/jupyterhub/jupyterhub-idle-culler/blob/main/RELEASE.md
- https://github.com/jupyterhub/jupyterhub-idle-culler/blob/3d9b0e92e7f973800854c4e6b42f906e79e261e6/jupyterhub_idle_culler/__init__.py#L23

**Comment by manics** [comment]
Isn't versioneer easier to use since you don't need to do anything other than create the Git tag?

**Comment by consideRatio** [comment]
I've never learned or understood versioneer to feel comfortable with it, so in that sense its not easier.

We can stick with it. I appreciate the systematic use of `tbump` which can be used in all our repos reliably, but I see that the RELEASE.md reflects versioneer correctly here so if you or someone else wish to retain it lets do so!
