### ISSUE TITLE
redirect loop with externally-managed TraefikRedisProxy using local Docker setup

### ISSUE THREAD

**Issue by kellyrowland** [jupyterhub/traefik-proxy#237]
### Bug description

I am trying to set up a local Jupyterhub instance using using TraefikRedisProxy, where Jupyterhub, Traefik, and Redis each have their own container and all three containers are brought up with Docker Compose. When attempting to spawn a server, I eventually get "500 : Internal Server Error Redirect loop detected."

### How to reproduce

1. Build jupyterhub container with `docker build -t jupyterhub-demo-redis .` 
2. Run `docker-compose up redis traefik jupyterhub`
3. Navigate to `http://127.0.0.1:8081/` in a browser
4. Enter arbitrary credentials and click on "Sign In"

I've included the `Dockerfile`, `docker-compose.yml`, `jupyterhub_config.py`, and `traefik.toml` files in the `files.tgz` archive attached:

[files.tgz](https://github.com/jupyterhub/traefik-proxy/files/14607994/files.tgz)

#### Expected behaviour

I expected a server to spawn and then to be able to launch a notebook.

#### Actual behaviour

The server progress bar eventually moves to the point where it looks to have completed, the text on the spawn-pending page changes to say "Server ready at /user/\<username\>", then the 500 error comes up.

### Your personal set up

- Installing the latest commit of the `traefik-proxy` repo `main` branch via `pip` in the Jupyterhub image
- Tested with Jupyterhub 3 and 4, same results for both versions
- DummyAuthenticator
- SimpleSpawner
- Traefik 2.11
- Redis 7.2
- Using Docker Desktop 4.17.0 on macOS Monterey 12.7.2

Container logs attached:

[jupyterhub.log](https://github.com/jupyterhub/traefik-proxy/files/14607999/jupyterhub.log)
[traefik.log](https://github.com/jupyterhub/traefik-proxy/files/14608000/traefik.log)
[redis.log](https://github.com/jupyterhub/traefik-proxy/files/14608002/redis.log)

**Comment by minrk** [comment]
> Navigate to http://127.0.0.1:8081/ in a browser

This is the private address for accessing the Hub, bypassing the proxy. It's not proxied, so requests will never be routed to anywhere but the Hub. In JupyterHub, you should always visit the _public_ address of your proxy. In your config, traefik does not yet have a public entrypoint defined.

Key points:

- Only the `traefik` service in your docker-compose needs to expose any ports. This is the only port of your application that should be accessible from outside your deployment. Ports don't need to be 'exposed' for the containers to talk to each other within the docker network.
- A traefik `entrypoint` is needed for the public interface of the proxy. This should not be the `auth_api` entrypoint, which is the internal endpoint for the traefik _api_. For JupyterHub with traefik, you always need two - one internal (e.g. `http`), one external (`auth_api`).
- only for demo purposes, but single-user servers must listen on a public IP to be connectable from outside the container

Here's an updated version of your files that works. The address to connect to is `localhost:8080`, which is the host port forwarded to port 80 in the traefik container, which is the `http` entrypoint - the public entrypoint (the name is not significant, only that it matches `traefik_entrypoint` in jupyterhub_config.py). I've removed all the other exposed ports to simplify things and show that only one is needed.

[files.zip](https://github.com/jupyterhub/traefik-proxy/files/14617431/files.zip)

**Comment by kellyrowland** [comment]
Thank you so much for the helpful (and quick!) response. This is my first try at setting this up, so I'm clearly still piecing things together conceptually, and I really appreciate the minimal working example and explanations here.

One note/question - the `files.zip` setup didn't quite work as I expected. I brought the containers up and pointed to `127.0.0.1:80`, and landed on a page that just said "It works!" I changed the traefik ports to `8000:8000` in `docker-compose.yml` and also changed the http entrypoint address to `:8000` - with those lined up, I got to Jupyterhub in the browser at `127.0.0.1:8000` and successfully spawned a server and launched a notebook.

**Comment by minrk** [comment]
> I brought the containers up and pointed to 127.0.0.1:80

Right. The URL you want to visit is `127.0.0.1:8080`. In the ports specification `8080:80`, that means 8080 on your machine (aka 'host'), which is the the port you visit, will be forwarded to port 80 in the container (the port traefik is listening on within its container). Everything is definitely easier when the two match, but I like to use different values to try to make it clearer which values in the configuration need to match _each other_.

The important thing for the traefik port is:

- the left port is the one you visit from _outside_ docker, and you can pick whatever you want without changing anything else inside your deployment
- the right port needs to match the http entrypoint port

**Comment by kellyrowland** [comment]
That makes sense; thank you for the thoughtful advice here. I'll mark this as closed now.
