### ISSUE TITLE
Common proxy profiling suite

### ISSUE THREAD

**Issue by minrk** [jupyterhub/traefik-proxy#28]
Like #27, it would be good to have a profiling suite, where, given a configured Proxy object, we can run some measurements to compare proxy implementations.

Things to measure:

1. add_route, delete_route, get_all_routes methods
1. request throughput (many small requests)
1. request throughput (few large requests)
1. websocket throughput

This will help us get a sense of the relative performance, and in particular we will be able to test things like multiple traefik instances and how/when that's helpful.

**Comment by GeorgianaElena** [comment]
@minrk, what do you think about this?
https://gist.github.com/GeorgianaElena/e8051623814178b5dbf8256ac2587918

Am I close to what you had in mind? (The requests should be concurrent, right?)

**Comment by minrk** [comment]
Yeah, that's great! To run the benchmarks they will indeed want to be done concurrently, probably with a limit on the concurrency (e.g. 1000 requests with max 10 concurrent)
