### ISSUE TITLE
Test with the littlest jupyterhub

### ISSUE THREAD

**Issue by minrk** [jupyterhub/traefik-proxy#32]
Perhaps before we go all the way to kubernetes in #26, we should try using this in [the littlest jupyterhub](https://the-littlest-jupyterhub.readthedocs.io/en/latest/). TLJH is a small, single-machine JupyterHub installation that already includes traefik as an edge proxy (pretty much just for letsencrypt support), in addition to configurable-http-proxy. We could use this traefik-proxy to eliminate the extra configurable-http-proxy service and use only traefik.

What it will look like:

1. remove configurable-http-proxy
2. traefik is already launched by systemd (not by `TraefikProxy.start()` here, so no 'static configuration' would be loaded from the code in this repo), so static config would have to be created in tljh.
3. probably use the toml implementation in #31. Alternately, we would need to add and run an etcd service

**Comment by GeorgianaElena** [comment]
@minrk, I've added new commits addressing your comments in the PR opened on tljh, if you want to take a look.

**Comment by GeorgianaElena** [comment]
@minrk, there's the ```test_long_username``` that fails intermittently in tljh.
From the logs it seems that the timeout to wait for a route (20s currently) ends before the route is actually added. Assuming is not something else, I believe it would be good to increase this timeout since we are dealing with I/O operations. Do you agree?

**Comment by minrk** [comment]
Yeah, go ahead and increase the timeout on the test to see if it helps.

**Comment by GeorgianaElena** [comment]
@minrk, thanks a lot for solving the issues with the credentials. Everything seems to work now :confetti_ball:
