### ISSUE TITLE
custom proxy tests with only proxy fixture

### ISSUE THREAD

**Issue by minrk** [jupyterhub/traefik-proxy#35]
#27 made the proxy tests more reusable, but I think we can refine it a little more.

In particular, I would like to get to a place where writing a new collection of proxy tests requires defining exactly one thing: the proxy fixture.

A proxy test file should only have to look like:

```python
# test_configurable_http_proxy.py
import pytest
from proxytest import *  # imports the test functions

@pytest.fixture
def proxy(request):
    proxy = ConfigurableHTTPProxy(...)
    ...
    try:
        yield proxy
    finally:
        # shutdown proxy
```

The rest should be taken care of. This means that other fixtures used in the tests (e.g. launch_backend or app) should not need to be defined. It would even be ideal if we could do without the `app` fixture altogether.

Let's try to make the etcd tests this way, and see how it goes.

**Comment by GeorgianaElena** [comment]
@minrk, I don't see how we could test ```check_routes``` without the ```app``` fixture... 
All the other tests are independent of this fixture, so I guess we could move ```test_check_routes``` to another file. This way the old tests will only require defining a proxy fixture and this one an ```app``` fixture. What do you think?

**Comment by minrk** [comment]
Indeed, that would be a bit complicated. We could do it by mocking the Users and Services objects and testing with those, but that's a lot to mock out. Would you like to try that? I'm happy with moving test_check_routes out of the proxytest for now, but it would probably be good to aim for that eventually.

**Comment by minrk** [comment]
If you like, I can have a look at the necessary mocks first if that would help.
