### ISSUE TITLE
Enabling Traefik w/ HTTPS JupyterHub

### ISSUE THREAD

**Issue by rubysown** [jupyterhub/traefik-proxy#55]
Hi, I am a little confused on how to enable HTTPS with Traefik & JuypterHub. 

Upon enabling the correct entryPoint for 443, it doesn't serve it over SSL it just uses the 443 port. From what I saw, we had to do this under the Frontends, but I'm unsure of how to do that with the dynamic system. I've pasted my config below, some values are 'x' to be censored.

Here's my relevant config in jupyterhub_config.py:
```
from jupyterhub_traefik_proxy import TraefikTomlProxy
c.TraefikTomlProxy.traefik_api_password = "x"
c.TraefikTomlProxy.traefik_api_username = "x"
c.TraefikTomlProxy.toml_dynamic_config_file = "/etc/traefik.toml"
c.JupyterHub.proxy_class = TraefikTomlProxy
```

Here's my traefik.toml:

```
defaultentrypoints = [ "http", "https" ]

[api]
dashboard = true
entrypoint = "auth_api"

[wss]
protocol = "https"

[file]
filename = "rules.toml"
watch = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/x/x/ssl.crt"
      keyFile = "/etc/x/x/ssl.key"

[entryPoints.auth_api]
address = ":8099"

[frontends.frontend__2F.routes.test]
rule = "PathPrefix:/"
data = "{\"hub\": true}"

[entryPoints.auth_api.auth.basic]
users = [ "x:x",]

[backends.backend__2F.servers.server1]
url = "http://x-x.x.x.x:8081"
weight = 1
```

**Comment by GeorgianaElena** [comment]
Hi @rubysown! Thanks for reaching out!

There is the ```should_start``` configuration option that I don't see set in your ```jupyterhub_config.py``` sample.

By default, this option is **True**, meaning that the Hub will be the one in charge of starting and stopping the proxy, in which case only the *http* and *auth_api* entrypoints will be available (in this case, even if you provide your own static configuration file, the proxy will override it with its default config).

However, if you want to manage the proxy externally and provide your own static configuration for traefik (through a *traefik.toml* file), you can set the ```should_start``` option to be **False**:
```
c.TraefikTomlProxy.should_start = False
```
This allows you to create your own static configuration file for traefik where you can define the **https** entrypoint (just like you did in the *traefik.toml* example you provided).

Keep in mind that the static configuration is the one that sets up the configuration to the entrypoints and you can think of the dynamic configuration as being the proxy's routing table.
So, in the jupyterhub_config.py, you should have something like this:
```
c.TraefikTomlProxy.toml_static_config_file = "/etc/traefik.toml"
c.TraefikTomlProxy.toml_dynamic_config_file = "/path/to/rules.toml" 
# this file needs to exist when starting traefik (but it can be empty).
```
Traefik allows you to have the static and dynamic config in the same file, but for *TraefikTomlProxy* we decided to keep them separate (checkout the discussion here: https://github.com/jupyterhub/traefik-proxy/issues/21), so I'd suggest setting both ```toml_static_config_file``` and ```toml_dynamic_config_file``` in ```jupyterhub_config.py``` and remove anything related to the frontends and backends from the static config file.

Based on these observations, I managed to get HTTPS working with TraefikTomlProxy and JuypterHub by changing just few things in the configuration you provided:

1. In **jupyterhub_config.py**:
```
c.TraefikTomlProxy.should_start = False #mark the proxy as being externally managed''
c.TraefikTomlProxy.toml_static_config_file = "/etc/traefik.toml
c.TraefikTomlProxy.toml_dynamic_config_file = "/path/to/rules.toml
```

2. In **traefik.toml**:
Here everything looks great, except that the piece below related to the frontends and backends shouldn't be here, but in the dynamic config file (usually added by JupyterHub and not by hand)

```
[frontends.frontend__2F.routes.test]
rule = "PathPrefix:/"
data = "{\"hub\": true}"

[backends.backend__2F.servers.server1]
url = "http://x-x.x.x.x:8081"
weight = 1
```

You could also add these two lines to get more info from traefik:

```
debug = true
logLevel = "INFO"
```

3. Create an empty **rules.toml** in the location specified through "toml_dynamic_config_file"

Now you can use JupyterHub with TraefikTomlProxy and https following this steps:

1. **Start traefik** with the static config file you provided:
```
$ traefik -c /etc/traefik.toml 
(you need root access for port 443)
```
2. **Start JupyterHub** with the *jupyterhub_config.py*:
```
$ jupyterhub --ip 127.0.0.1 --port=80 (your http port) -f jupyterhub_config_toml.py
(make sure jupyterhub can edit rules.toml)
```
Now you can access http://127.0.0.1:80 in your browser and you'll be automatically redirected to https://127.0.0.1:443.

Please let me know if this works for you or if you have any other questions.

**Comment by rubysown** [comment]
@GeorgianaElena thank you very much, I was able to get it working after reworking my config like you described. We are very excited to try it out! Thanks again!

**Comment by chuckmandu** [comment]
Since redirection of HTTP-->HTTPS is likely one of the most common configuration tweaks, it would be useful to see an example in the documentation for configuration when using Traefik 2 (middlewares, etc.);  I'm struggling with this right now. Will include my configuration when I get it working.
