### ISSUE TITLE
[ASK] Traefik configuration example for multiple node server

### ISSUE THREAD

**Issue by sundh4** [jupyterhub/traefik-proxy#58]
Dear All,

I believe traefik-proxy able to load balance across multiple Jupyter server using single Jupyterhub.
The topology would be like this image: https://cdn-images-1.medium.com/max/1600/1*A--P2mM21Cj6gfWImInnww.png

Let say a single user accessing 1 jupyterhub, then the traefik proxy sent the request to available server (let say i have 2 server A & B).
I read the doc, but i can't find out how to setup this (I believe it used etcd config). It is not clear for me. Please help me regarding this.

Thanks in advance.

**Comment by minrk** [comment]
TraefikProxy doesn't change how routing works in JupyterHub. It is a different *implementation* of the existing routing when using configurable-http-proxy.

So in JupyterHub, user A has a server and user B has a server. The proxy routes `/user/a/` to server A and `/user/b/` to server B. If a single user has multiple servers, they will be on different URLs using JupyterHub's named servers feature, e.g. `/user/a/gpu` and `/user/a/tensorflow`.
