### ISSUE TITLE
Missing format in .install warnings

### ISSUE THREAD

**Issue by vhaldemar** [jupyterhub/traefik-proxy#67]
Hello!
There are missing `.format` in warnings about verifying checksum of deps.
For example, https://github.com/jupyterhub/traefik-proxy/blob/6a61eab6a2b2b61fbedc2d0247d12ef59005a5a7/jupyterhub_traefik_proxy/install.py#L106

Example of warning:
```
/pyenv/versions/temp-venv/lib/python3.7/site-packages/jupyterhub_traefik_proxy/install.py:145: UserWarning: Couldn't verify checksum for etcd-v{etcd_version}-{plat}.
  warnings.warn("Couldn't verify checksum for etcd-v{etcd_version}-{plat}.")
```

**Comment by GeorgianaElena** [comment]
Thanks a lot for reporting this @vhaldemar :four_leaf_clover:
