### ISSUE TITLE
PYPI_PASSWORD set in Travis, but not used for CD in .travis.yml

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/traefik-proxy#86]
I've created a PYPI_PASSWORD environment variable available for pushed travis builds, that contains a PyPI deployment token, created and revokable by the PyPI account called `jupyterhub-bot`.

**Comment by GeorgianaElena** [comment]
Yaay :heart: Thanks @consideRatio. Now we can apply the release pattern from authenticators here too :confetti_ball:

**Comment by consideRatio** [comment]
You always bring a lot of warm energy :) I appreciate that!

**Comment by GeorgianaElena** [comment]
Closed by https://github.com/jupyterhub/traefik-proxy/pull/89
