### ISSUE TITLE
Install utility options

### ISSUE THREAD

**Issue by jtpio** [jupyterhub/traefik-proxy#92]
Using the latest `jupyterhub-traefik-proxy` (0.1.4), it looks like the install utility command mentioned in the docs (https://jupyterhub-traefik-proxy.readthedocs.io/en/latest/install.html#traefik-proxy-installation
) does not proceed if the target directory already exists:

```
$ python -m jupyterhub_traefik_proxy.install --output=/usr/local/bin
Dependencies directory already exists.
```

This seems most likely related to this check?

https://github.com/jupyterhub/traefik-proxy/blob/22aaeeb2ff69fc8ebb30f3d6a683be540c3638e4/jupyterhub_traefik_proxy/install.py#L375

Should the installer be able to use an existing directory to install the binaries?

**Comment by jtpio** [comment]
Also it looks like `--traefik` (and similarly etcd and consul) must be explicitly passed as an argument.

**Comment by jtpio** [comment]
The existing directory is actually not an issue, I think it was just related to passing `--traefik` as a command line argument.

**Comment by GeorgianaElena** [comment]
> Also it looks like --traefik (and similarly etcd and consul) must be explicitly passed as an argument.

@jtpio, yes they must be explicitly passed. This was introduced in https://github.com/jupyterhub/traefik-proxy/pull/76 and unfortunately I didn't update the docs to reflect this info. Will do it now.

> Should the installer be able to use an existing directory to install the binaries?

Yes it should. That check you've mentioned is just to print out `Dependencies directory already exists` message to the console. The installation should happen regardless of this check (I think there's also a test for this use-case). Can you please double check if there's no traefik binary in that directory?

**Comment by jtpio** [comment]
PR incoming :)

**Comment by jtpio** [comment]
Opened https://github.com/jupyterhub/traefik-proxy/pull/93 to update the docs.
